openapi: 3.1.0
info:
  version: 1.0.0
  title: Blended 115
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: >
    Our amazing API for blended 115
tags:
  - name: Products
    description: Some products API
servers:
  - url: http://localhost:4040
  - url: #посилання на задеплоєний сайт
paths:
  /products:
    get:
      $ref: ../swagger/paths/


components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
